"""Контракты артефактов disputatio/v1|v2: pydantic-модели и чистые валидаторы.

Публичный API волны 1 ([DESIGN-010]): потребители импортируют модели,
enum'ы, функции валидации, порты и константы причин только отсюда,
не из подмодулей.
"""

from disputatio.contracts.base import (
    SCHEMA_V1,
    SCHEMA_V2,
    ArtifactBase,
    ArtifactChild,
    Role,
)
from disputatio.contracts.checklist import (
    ArtifactEvidence,
    ChecklistItem,
    EvidenceRef,
    GateEvidence,
)
from disputatio.contracts.checklists_catalog import (
    CHECKLIST_BY_CONTOUR,
    CHECKLIST_TEXT,
    PAIR_CHECKLIST,
    SPEC_CHECKLIST,
)
from disputatio.contracts.decision import Decision, Outcome
from disputatio.contracts.events import Event, EventSource, EventType
from disputatio.contracts.pipeline import (
    ALLOWED_TRANSITIONS,
    SCHEMA_PIPELINE_V1,
    AppendOnlyEntry,
    DocumentPaths,
    EvidenceLink,
    FileRef,
    IntegritySnapshot,
    NextAction,
    OperatorDecision,
    PipelineArtifactBase,
    PipelinePhase,
    PipelineState,
    SessionOutcome,
    SessionRecord,
    Transition,
    TransitionReason,
    validate_relative_path,
)
from disputatio.contracts.ports import (
    AgentAdapter,
    AgentTurn,
    BoundaryVerdict,
    EventSink,
    PipelineStateStore,
    RoundBoundaryPolicy,
    SessionLifecyclePolicy,
    StateStore,
    Verifier,
)
from disputatio.contracts.proposal import (
    ProposalFrontmatter,
    ProposalParseError,
    SelfDeclaredStatus,
    parse_proposal,
)
from disputatio.contracts.review import Issue, Review, Severity, Verdict
from disputatio.contracts.session import (
    AgentRef,
    BudgetUsed,
    Limits,
    Mode,
    SessionPhase,
    SessionState,
    TaskSpec,
)
from disputatio.contracts.validation import (
    REASON_APPROVE_ON_FAILED_GATES,
    REASON_APPROVE_WITH_CHECKLIST_FAIL,
    REASON_APPROVE_WITH_SUBSTANTIVE_ISSUE,
    REASON_CHECKLIST_FAIL_ISSUE_SEVERITY_TOO_LOW,
    REASON_CHECKLIST_FAIL_UNKNOWN_ISSUE_ID,
    REASON_CHECKLIST_FAIL_WITHOUT_ISSUE_IDS,
    REASON_CHECKLIST_ID_MISMATCH,
    REASON_CHECKLIST_PASS_CONTRADICTS_S1,
    REASON_EMPTY_CHECKED,
    REASON_NO_SUBSTANTIVE_ISSUES,
    REASON_PAIR_ISSUE_MISSING_DEFECT_CLASS,
    ReviewAcceptance,
    check_checked_nonempty,
    check_substantive_issues,
    check_verdict_vs_verification,
    degrade_unevidenced_issues,
    validate_doc_review,
    validate_review,
)
from disputatio.contracts.verification import (
    DiffStats,
    GateResult,
    GateStatus,
    OverallStatus,
    VerificationReport,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "CHECKLIST_BY_CONTOUR",
    "CHECKLIST_TEXT",
    "PAIR_CHECKLIST",
    "REASON_APPROVE_ON_FAILED_GATES",
    "REASON_APPROVE_WITH_CHECKLIST_FAIL",
    "REASON_APPROVE_WITH_SUBSTANTIVE_ISSUE",
    "REASON_CHECKLIST_FAIL_ISSUE_SEVERITY_TOO_LOW",
    "REASON_CHECKLIST_FAIL_UNKNOWN_ISSUE_ID",
    "REASON_CHECKLIST_FAIL_WITHOUT_ISSUE_IDS",
    "REASON_CHECKLIST_ID_MISMATCH",
    "REASON_CHECKLIST_PASS_CONTRADICTS_S1",
    "REASON_EMPTY_CHECKED",
    "REASON_NO_SUBSTANTIVE_ISSUES",
    "REASON_PAIR_ISSUE_MISSING_DEFECT_CLASS",
    "SCHEMA_PIPELINE_V1",
    "SCHEMA_V1",
    "SCHEMA_V2",
    "SPEC_CHECKLIST",
    "AgentAdapter",
    "AgentRef",
    "AgentTurn",
    "AppendOnlyEntry",
    "ArtifactBase",
    "ArtifactChild",
    "ArtifactEvidence",
    "BoundaryVerdict",
    "BudgetUsed",
    "ChecklistItem",
    "Decision",
    "DiffStats",
    "DocumentPaths",
    "Event",
    "EventSink",
    "EventSource",
    "EventType",
    "EvidenceLink",
    "EvidenceRef",
    "FileRef",
    "GateEvidence",
    "GateResult",
    "GateStatus",
    "IntegritySnapshot",
    "Issue",
    "Limits",
    "Mode",
    "NextAction",
    "OperatorDecision",
    "Outcome",
    "OverallStatus",
    "PipelineArtifactBase",
    "PipelinePhase",
    "PipelineState",
    "PipelineStateStore",
    "ProposalFrontmatter",
    "ProposalParseError",
    "Review",
    "ReviewAcceptance",
    "Role",
    "RoundBoundaryPolicy",
    "SelfDeclaredStatus",
    "SessionLifecyclePolicy",
    "SessionOutcome",
    "SessionPhase",
    "SessionRecord",
    "SessionState",
    "Severity",
    "StateStore",
    "TaskSpec",
    "Transition",
    "TransitionReason",
    "Verdict",
    "VerificationReport",
    "Verifier",
    "check_checked_nonempty",
    "check_substantive_issues",
    "check_verdict_vs_verification",
    "degrade_unevidenced_issues",
    "parse_proposal",
    "validate_doc_review",
    "validate_relative_path",
    "validate_review",
]
